### ISSUE TITLE
module.invalidable = true

### ISSUE THREAD

**Issue by Globik** [FranckFreiburger/module-invalidate#1]
I think it would be nice if the 'module.invalidable = true' by default always were to set to true.
Is there any reason explicitly to write this 'module.invalidable=true'? Is there any use case for 'module.invalidable=false'?

**Comment by Globik** [comment]
Let's say I have process.env.development=true and all modules by default are 'invalidable==true'.
And when I have process.env.development=production so I simply will not be using this module-invalidate and all will be happy with it.
This module is good enough, with innovative Proxy element. But always in every module writing the property 'invalidable' is not so good if in a directory you have above 100 javascript files.

**Comment by Globik** [comment]
Now I understand why I should to write this module.invalidable=true
I tried to remove the part of code where is this property is. And then this module if lays near with other modules in a node_modules directory it beginns to break the native functionality of other modules. Throws the errors at run time. It's a very pitty.
https://github.com/Globik/module-invalidate-2/blob/master/index.js

**Comment by FranckFreiburger** [comment]
In fact, since module-invalidate cannot predict the behavior of your module (in term of resource allocation/deallocation) it is mandatory for module-invalidate to keep the most neutral behavior: module.invalidable=false
